apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: kcp
  namespace: rhn-support-csams
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: control-plane-service
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: kcp
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: kcp-
      labels:
        build.appstudio.openshift.io/application: control-plane-service
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: kcp
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: rhn-support-csams
    spec:
      params:
      - name: git-url
        value: https://github.com/kcp-dev/kcp
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:rhn-support-csams-kcp-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:472c04f0800aa791267b047bc0bbc38c357b2d6c
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: kcp/$(tt.params.git-revision)
    status: {}
status: {}
